---

- name: Ensure htpasswd directory
  file:
    path: "{{ nginx_htpasswd_path }}"
    state: directory
    owner: root
    group: "{{ root_group }}"
    mode: 0755

- name: Add managed htpasswd config file (if any)
  template:
    src: htpasswd.j2
    dest: "{{ nginx_htpasswd_path }}/{{ item.name }}"
    mode: 0644
  with_items: "{{ nginx_htpasswd }}"
  notify:
    - reload nginx

  
